```{python}
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from projtools.data import Data

data = Data()

#check that the data is consistent across the different geographical breakdowns
```

# Categories and Offences
First, we need to check if the categories and offences are consistent across the different data sets, so that we know the data is recorded consistently and we can compare it as such

```{python}
trial = list(data.lsoa.index.get_level_values(3).unique().sort_values())
trial.insert(3, 'N/A')
trial.insert(8, 'N/A')
cat_names = {'borough_cat': list(data.borough.index.get_level_values(0).unique().sort_values()), 'ward_cat': list(data.ward.index.get_level_values(2).unique().sort_values()), 'LSOA_cat': trial}
cats = pd.DataFrame(data=cat_names)
cats
```

As can be seen in the data frame above, while the categories are consistent across the ward and borough data sets, there are two categories missing from the LSOA data set. These are the Sexual Offences and the Historical Fraud and Forgery categories. The Sexual Offences category is removed for discretion, but there is no explanation for why Historical Fraud and Forgery is missing. One possible explanation is that this crime has not been recorded at local police stations since 2013, and so has been removed from the LSOA data set. This does not explain the category's presence in the other data sets, however.

```{python}
lsoa_off = list(data.lsoa.index.get_level_values(4).unique().sort_values())
lsoa_off.insert(19, 'N/A')
lsoa_off.insert(30, 'N/A')
lsoa_off.insert(43, 'N/A')

offs = {'borough_level': list(data.borough.index.get_level_values(1).unique().sort_values()), 'ward_level': list(data.ward.index.get_level_values(3).unique().sort_values()), 'lsoa_level':lsoa_off}
off_names = pd.DataFrame(data=offs)
off_names
```

The borough and ward data sets are consistent in the offence classifications. However, the LSOA data set is missing the following offences: Rape, Other Sexual Offences and Historical Fraud and Forgery. This is expected as it is also missing the categories that these offences belong to. The fact that these offences are not being recorded will have to be taken in to account when considering consistency across data sets.


## Comparing Datasets

In the following code, I will look for differences in reported crimes between the borough-, ward- and LSOA-level.


### Comparing the same offence by borough

```{python}
pd.DataFrame(data.borough.loc[:, 'Arson', :].T.groupby(level='year').sum().sum())
```

The above dataframe shows the total number of Arson offences across the entirety of the borough dataset.

```{python}
pd.DataFrame(((data.borough.loc[:, 'Arson', :].T.groupby(level='year').sum().sum()) - (data.ward.loc[:, :, :, 'Arson', :].groupby(level=[3]).sum().T.sum())).sort_values(ascending=False))
```

```{python}
data.borough.loc[:, 'Arson', 'Hillingdon'].T.groupby(level='year').sum()
```

```{python}
data.borough.loc[:, 'Arson', 'London Heathrow and London City Airports'].T.groupby(level='year').sum()
```

```{python}
# np.(data.borough.loc[:, 'Arson', 'Hillingdon'].T.groupby(level='year').sum()) - np.
(data.ward.loc[:, :, :, 'Arson', 'Hillingdon'].sum().T.groupby(level='year').sum())
```

```{python}
(data.ward.loc[:, :, :, 'Arson', :].groupby(level=[3]).sum().T.sum())
```

```{python}
(data.borough.sum() - data.ward.sum()).sort_values(ascending = False)
```

```{python}
(data.borough.sum() - data.lsoa.sum()).sort_values(ascending = False)
```

```{python}
data.borough.sum()
```

```{python}
data.borough
data.ward
```

```{python}
# data.ward.loc[:, :, 'Historical Fraud and Forgery', :, :].T.groupby(level='year').plot()
```

```{python}
data.lsoa
```
