---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
  widgets:
    application/vnd.jupyter.widget-state+json:
      state: {}
      version_major: 2
      version_minor: 0
---

# MultiIndex - a short guide

This is a short guide of using the MultiIndex, for more detail see these resources:
- [Nice guide](https://datascientyst.com/use-loc-and-multi-index-in-pandas/)
- [Slightly scary but detailed pandas user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced-indexing-with-hierarchical-index)

```{python}
import numpy as np
import pandas as pd
from projtools.data import Data
import matplotlib.pyplot as plt
plt.style.use('projtools/rose-pine.mplstyle')
```

```{python jupyter={'outputs_hidden': True}}
data = Data()
```

```{python jupyter={'outputs_hidden': True}}
data.ward
```

We can get all of the rows for a given ward_name like this:

```{python jupyter={'outputs_hidden': True}}
data.ward.loc["Heathrow Villages"]
```

It's also easy to filter to a particular year, like this:

```{python}
data.ward.loc["Heathrow Villages", "2010"]
```

To get the rows for a given ward_code we have to tell pandas what level we are interested in, there are a few ways of doing this:

```{python jupyter={'outputs_hidden': True}}
data.ward.loc[:, "E05013570", :]
# NB the slightly more verbose version of this is:
# data.ward.loc[:, "E05013570", :, :, :]
```

This works nicely but things get a little more complicated if we then want to filter by year when we're not using the first index level (ward_name):

```{python jupyter={'outputs_hidden': True}}
# Using the same loc syntax as above we can do the following...
data.ward.loc[(slice(None), "E05013570"),"2010"]
# NB the more verbose version of this is:
# data.ward.loc[(slice(None), "E05013570", slice(None), slice(None), slice(None)), "2010"]
```

```{python}
# Alternatively, we can do this:
data.ward.loc[:, "E05013570", :]["2010"]
```

Using `slice(None)` can be quite verbose if you want to specify one of the later layers, for example the category of crime and also select the year:

```{python jupyter={'outputs_hidden': True}}
data.ward.loc[("Heathrow Villages", slice(None), slice(None), "Other Theft"), "2010"]
```

There is a slightly neater alternative for this situation:

```{python jupyter={'outputs_hidden': True}}
idx = pd.IndexSlice
data.ward.loc[idx["Heathrow Villages", :, :, "Other Theft"], "2010"]
```

With both of these methods you can of course select multiple values for each level:

```{python jupyter={'outputs_hidden': True}}
data.ward.loc[idx["Heathrow Villages", :, :, ["Other Theft", "Theft from a Motor Vehicle"]], ["2010","2021"]]

# Alternatively using a tuple and slice(None)...
# data.ward.loc[("Heathrow Villages", slice(None), slice(None), ["Other Theft", "Theft from a Motor Vehicle"]), ["2010", "2021"]]
```

In the same way we can select from multiple levels in the row index we can do the same with the columns:

```{python}
data.ward.loc[idx["Heathrow Villages", :, :, ["Other Theft", "Theft from a Motor Vehicle"]], idx[["2010","2021"], ["01", "05", "10"]]]
```

Above, we have learnt how to make complex data selections using the `MultiIndex`. The power of this can then be realised further by using `groupby`, aggregation functions and more:

```{python jupyter={'outputs_hidden': True}}
# Here we are selecting all of the "Other Theft" crimes in the Heathrow Villages ward in the Hillingdon borough.
# `.T` splits along the columns so that we can groupby year, .sum() gives us a total for each year
theft_heathrow_hill = data.ward.loc["Heathrow Villages", :, :, "Other Theft", "Hillingdon"].T.groupby(level="year").sum()
theft_heathrow_hill
```

```{python}
theft_heathrow_hill.plot()
```

```{python}
theft_heathrow_all = data.ward.loc["Heathrow Villages", :, :, "Other Theft"].T.groupby(level="year").sum()
theft_heathrow_all.plot()
```

```{python}
data.ward.loc["Heathrow Villages", :, :, "Other Theft"].T.groupby(level="year").sum().sum(axis=1).plot()
```
