# Categories and Offences
So that we can be confident in our analysis and interpretation of the data, it is important to check for consistency across the datasets. In theory, as all wards sit within a borough and all LSOAs sit within a ward and borough, the total number of recorded crimes should be the same across all three datasets. We will go on to discover that there are in fact systematic discrepancies.
```{python}
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from projtools.data import Data

data = Data()
```

```{python}
trial = list(data.lsoa
                 .index
                 .get_level_values(3)
                 .unique()
                 .sort_values())
trial.insert(3, 'N/A')
trial.insert(8, 'N/A')
borough_cat = list(data.borough
                       .index
                       .get_level_values(0)
                       .unique()
                       .sort_values())
ward_cat = list(data.ward
                    .index
                    .get_level_values(2)
                    .unique()
                    .sort_values())
cat_names = {'borough_cat': borough_cat, 'ward_cat': ward_cat, 'LSOA_cat': trial}
cats = pd.DataFrame(data=cat_names)
cats
```

As can be seen in the data frame above, while the categories are consistent across the `ward` and `borough` data sets, there are two categories missing from the LSOA data set.

These are the Sexual Offences and the Historical Fraud and Forgery categories. The Sexual Offences category is removed for privacy purposes, but there is no explanation for why Historical Fraud and Forgery is missing. One possible explanation is that this crime has not been recorded at local police stations since 2013, and so has been removed from the `lsoa` data set. This does not explain the category's presence in the other data sets, however.

```{python}
lsoa_off = list(data.lsoa.index.get_level_values(4).unique().sort_values())
lsoa_off.insert(19, 'N/A')
lsoa_off.insert(30, 'N/A')
lsoa_off.insert(43, 'N/A')

offs = {'borough_level': list(data.borough.index.get_level_values(1).unique().sort_values()), 'ward_level': list(data.ward.index.get_level_values(3).unique().sort_values()), 'lsoa_level':lsoa_off}
off_names = pd.DataFrame(data=offs)
off_names
```

The `borough` and `ward` datasets are consistent in the offence classifications. However, the `lsoa` dataset is missing the following offences: Rape, Other Sexual Offences and Historical Fraud and Forgery. This is expected as it is also missing the categories that these offences belong to. The fact that these offences are not being recorded will have to be taken in to account when considering consistency across datasets.


## Comparing Datasets

In the following code, I will look for differences in reported crimes between the borough, ward and LSOA level.

```{python}
bor_ward_diff = (data.borough.loc[:,:,:].groupby('offence').sum() - data.ward.loc[:,:,:,:,:].groupby('offence').sum()).T.sum().sort_values(ascending = False)
bor_ward_df = bor_ward_diff.to_frame('difference')

bor_ward_df.head(15)
```

The above dataframe shows the difference in recorded crimes between the `borough` and `ward` datasets, separated by the offence. It seems that there is quite a large difference between the recorded crimes in the two datasets.

One would assume that the offences with the largest differences would be those that are less geographically contained, such as __Obscene Publication__ or __Fraud or Forgery Associated with Driver Records__. Instead, the top ten values are offences that tend to be committed in very specific locations, such as __Rape__ or __Theft__.

We have not been able to ascertain the reason for these significant discrepancies. Perhaps it is just down to incomplete recording in the first instance.

```{python}
bor_ward_diff.sum()
```

The total difference in recorded crimes between the `ward` and `borough` datasets is __227673.0__

```{python}
bor_lsoa_diff = (data.borough.loc[:,:,:].groupby('offence').sum() - data.lsoa.loc[:,:,:,:,:].groupby('offence').sum()).T.sum().sort_values(ascending = False)
bor_lsoa_df = bor_lsoa_diff.to_frame('difference')

bor_lsoa_df.head(15)
```

The above dataframe shows the difference in recorded crimes between the `borough` and `lsoa` datasets, separated by the offence. It seems that there is also quite a large difference these two datasets.

The ten highest differences are the same as with the `ward` dataset, allowing for the fact that __Rape__ and __Other Sexual Offences__ are not present in the `lsoa` dataset.

We have considered that given an LSOA is roughly 1,000 people, protecting the privacy of the victims could be a feasible explanation. However, we know that the Sexual Offences category has been removed for this reason so if this was the reason presumably these offences would be removed completely from the LSOA data.

It may be more plausible that it is simply down to reporting practices; there may not be a requirement for officers to input the ward or LSOA of the crime.

```{python}
bor_lsoa_diff.sum()
```

The total difference in recorded crimes between the `lsoa` and `borough` datasets is __206948.0__

```{python}
ward_lsoa_diff = (data.ward.loc[:,:,:,:,:].groupby('offence').sum() - data.lsoa.loc[:,:,:,:,:].groupby('offence').sum()).T.sum().sort_values(ascending = False)
ward_lsoa_df = ward_lsoa_diff.to_frame('difference')

ward_lsoa_df.head(15)
```

This dataframe shows the differences in the `lsoa` and `ward` datasets. Similar to the two previous dataframes, the seven highest differences are pretty much the same. The only difference is that the differences are a lot lower.

This seems to suggest that if a crime is recorded at the ward level, it is very likely to be recorded at the LSOA level too.

```{python}
ward_lsoa_diff.sum()
```

The total difference in recorded crimes between the `lsoa` and `ward` datasets is __3946.0__


Overall, there are areas of substantial inconsistency in the recorded crimes across the three datasets. As such, the `borough` dataset should be used for analysis of the data when looking at seasonal changes, as it appears to be more complete.


### Comparing the same offence by borough

```{python}
pd.DataFrame(data.borough
                 .loc[:, 'Arson', :]
                 .T
                 .groupby(level='year')
                 .sum()
                 .sum())
```

The above dataframe shows the total number of __Arson__ offences across the entirety of the `borough` dataset.

```{python}
borough_arson = (data.borough
                     .loc[:, 'Arson', :]
                     .T
                     .groupby(level='year')
                     .sum()
                     .sum())
ward_arson = (data.ward
                  .loc[:, :, :, 'Arson', :]
                  .groupby(level=[3])
                  .sum()
                  .T
                  .sum())
pd.DataFrame((borough_arson - ward_arson).sort_values(ascending=False))
```

The above data frame shows the difference in reported Arson offences between the `borough` and `ward` datasets.

It seems that there is more reports made in the `borough` dataset consistently, other than in Hillingdon. One possible explanation for this is that the `borough` dataset contains a __London Heathrow and London City Airports__ borough, which the `ward` dataset does not.

Heathrow Airport is in the __Hillingdon__ borough and London City Airport is in __Newham__. This means that the Arson offences are being split between these __borough__ values, leading to less reports in the `borough` dataset compared to the `ward` dataset for the Hillingdon and Newham boroughs.

The `ward` dataset does include a __Aviation Security (SO18)__ borough, however. This is in reference to the Heathrow Airport.

```{python}
bor_hillingdon = ((data.borough
                       .loc[:, 'Arson', ['Newham', 'Hillingdon']]
                       .T
                       .groupby(level='year')
                       .sum()
                       .T
                       .sum())
                       .to_frame('Arson'))
    
bor_heathrow_londoncity = (data.borough
                               .loc[:, 'Arson', 'London Heathrow and London City Airports']
                               .T
                               .groupby(level='year')
                               .sum())
ward_hillingdon = ((data.ward
                        .loc[:, :, :, 'Arson', ['Newham','Hillingdon','Aviation Security (SO18)']]
                        .sum()
                        .T
                        .groupby(level='year')
                        .sum())
                        .to_frame('Arson Offences'))
```

```{python}
bor_hillingdon
```

The above data frame is of all the Arson offences in the `borough` dataset in the __Hillingdon__ and __Newham__ boroughs.

```{python}
bor_heathrow_londoncity
```

The above data frame is of all the Arson offences in the `borough` dataset in the __London Heathrow and London City Airports__ borough.

```{python}
ward_hillingdon
```

The above dataframe is of all the Arson offences in the `ward` dataset in the __Hillingdon__ and __Newham__ boroughs.

```{python}
((bor_hillingdon['Arson'] + bor_heathrow_londoncity['Arson and Criminal Damage']) - ward_hillingdon['Arson Offences']).sum()
```

The above code adds together the records of arson in __Hillingdon__, __Newham__ and __London Heathrow and London City Airports__ (`borough` dataset) and takes away the records from the `ward` dataset for __Hillingdon__, __Newham__ and __Aviation Security (SO18)__ borough.

This leaves a difference of __12.0__.

This means that there is more reports in the `borough` dataset than the `ward` dataset.

```{python}
bor_hillingdon1 = ((data.borough
                        .loc[:, 'Arson', 'Hillingdon']
                        .T
                        .groupby(level='year')
                        .sum()
                        .T
                        .sum())
                        .to_frame('Arson'))
ward_hillingdon1 = ((data.ward
                         .loc[:, :, :, 'Arson', ['Hillingdon','Aviation Security (SO18)']]
                         .sum()
                         .T
                         .groupby(level='year')
                         .sum())
                         .to_frame('Arson Offences'))
((bor_hillingdon1['Arson'] + bor_heathrow_londoncity['Arson and Criminal Damage']) - ward_hillingdon1['Arson Offences']).sum()
```

When the same calculations are made, having removed __Newham__, a difference of __4.0__ remains. __8.0__ is exactly the value of the difference between the `ward` and `borough` datasets for `Newham`. This must mean that __4.0__ of the recorded offences concerning Heathrow Airport belong in __Hillingdon__, so the net difference is actually __2.0__, not __-2.0__.
